version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_central
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"

  keycloak_central:
    container_name: keycloak_central
    image: jboss/keycloak:9.0.3
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"

  sonarqube_central:
    container_name: sonarqube_central
    image: sonarqube:7.9.3-community
    environment:
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: admin
    ports:
      - "9000:9000"

  jaeger_central:
    container_name: jaeger_central
    image: jaegertracing/all-in-one:1.18.0
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"